server:
  port: ${vcap.application.port:9010}
eureka:
  client:
    serviceUrl:
      # defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
      defaultZone: https://eureka-server.apps-np.homedepot.com/eureka/
  instance:
    hostname: ${vcap.application.uris:localhost}
    nonSecurePort: 80
spring:
  profiles:
    active: default
endpoints:
  restart:
    enabled: true
  health:
    sensitive: false

logging:
  file: debug.log
  
hystrix:
  metrics:
    enabled: false
  
management:
  security:
    enabled: false
  